name = "Pengolod's Base Modpack"
author = "Pengolod"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50b9a0bd4efc347a9edec556e716cc8af26aa3ef2507df9baa9defd3dc30163e"

[versions]
fabric = "0.11.7"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17"]
