name = "Pengolod's Base Modpack 1.17.1"
author = "Pengolod"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01b1db1025894d70474837ec2c5cd01aea7663c7deaeb0193b870814f2f23971"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17"]
