# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: go install github.com/packwiz/packwiz@latest # runs during prebuild
    # command: echo 'start script'
