name = "Pengolod's Base Modpack 1.18.1"
author = "Pengolod"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbc980a5fc1d059ff6a530e3607e57d111183568e5710ad83f3f530f550fea10"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
