name = "Simple Voice Chat"
filename = "voicechat-fabric-1.17.1-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3459/642/voicechat-fabric-1.17.1-1.2.0.jar"
hash-format = "murmur2"
hash = "4262949151"

[update]
[update.curseforge]
file-id = 3459642
project-id = 416089
release-channel = "beta"
